Fix/issue 31
Rise-Vision/rise-financial pull request #32
Opened 2017-03-07 14:25 UTC by rodrigopavezi

@tejohnso please review. cheers

2017-03-07 14:49 UTC, tejohnso requested changes

2017-03-07 14:49 UTC, tejohnso commented on rise-financial-es6.js
> +      if ( !this._firebaseApp && !firebase.apps.length ) {
@rodrigopavezi If firebase has allready been initialized and the second test fails then this._firebaseApp isn't set. Shouldn't it be set to the existing instance that caused the second test to fail?

2017-03-07 19:20 UTC, rodrigopavezi commented
@tejohnso good catch. I have changed that. I have also fixed another issue with the JSONP callback so it will be unique per instance of the component. Please review. cheers

2017-03-07 20:54 UTC, tejohnso approved these changes

2017-03-08 14:50 UTC, stulees requested changes
@rodrigopavezi This needs a version bump and rebuild, thanks.

2017-03-08 15:55 UTC, rodrigopavezi commented
@stulees version bumped, please review. cheers

2017-03-08 15:58 UTC, stulees approved these changes

2017-03-08 15:58 UTC, stulees commented
@rodrigopavezi 👍

2017-03-08 15:58 UTC, merged