try populating instruments from localStorage when offline
Rise-Vision/rise-financial pull request #42
Opened 2017-04-26 15:58 UTC by settinghead

2017-04-26 16:53 UTC, stulees requested changes
@settinghead As well as corrections, there are missing deployment files. You need to run `gulp bump` and then run `npm run build`.

2017-04-26 16:53 UTC, stulees commented on rise-financial-es6.js
> +        this.firebaseConnected = snap.val();
@settinghead I think `firebaseConnected` should be added to "private" vars here - https://goo.gl/9oj1Fl and default to `true`. Also can you use the usual _ prefix,  `this._firebaseConnected`.

2017-04-26 16:53 UTC, stulees commented on rise-financial-es6.js
> +      connectedRef.on( "value", ( function onConnectionStateChanged( snap ) {
@settinghead You can use es6 `=>` here instead of `function`

2017-05-01 17:04 UTC, settinghead commented
@stulees code updated. Thanks.

2017-05-01 18:04 UTC, stulees commented
@settinghead Any test coverage possible? Thanks

2017-05-03 09:22 UTC, settinghead commented
@stulees added an integration test case.

2017-05-03 13:53 UTC, stulees approved these changes

2017-05-03 13:53 UTC, stulees commented
@settinghead Looks good 👍

2017-05-03 13:54 UTC, merged