Get real-time data from financial server
Rise-Vision/rise-financial pull request #6
Opened 2016-12-09 19:29 UTC by donnapep

2016-12-13 15:56 UTC, donnapep commented
@Rise-Vision/delivery Please review. Thx.

2016-12-14 15:59 UTC, stulees requested changes

2016-12-14 15:59 UTC, stulees commented on .gitignore
> +rise-financial.html
@donnapep I don't think we should ignore these files. When a designer uses Bower or npm to pull in this component, those files will be missing. They need to be able to use an ES5 version.

2016-12-14 16:08 UTC, donnapep commented on .gitignore
> +rise-financial.html
@stulees This is akin to when we were committing the `dist` folder, which created problems for us when we weren't even sure it was necessary. I think we're in a similar situation here. If a designer is already pulling this component in via Bower or similar, then I tend to think that it's not a stretch for them to run `gulp build`.

Given this, what do you think about leaving it out for now and adding them back in if it becomes an issue? It creates extra work for us by committing them.

2016-12-14 16:12 UTC, settinghead commented on .gitignore
> +rise-financial.html
You can also publish your bower or npm package so that it can contain these built files while leaving them out of the git history.

2016-12-14 16:14 UTC, stulees commented on .gitignore
> +rise-financial.html
@donnapep Not sure I follow how a designer running `gulp build` will resolve it. Can you clarify? I see this as a different situation to the `dist` folder. When a designer has created a project that uses this component, if we .gitignore these files, then these files will not be in the bower (or similar) package for their project.

2016-12-14 16:15 UTC, settinghead commented on rise-financial-es6.js
> +      realTime.params = this._getRealTimeParams( instruments, fields );
@donnapep I suppose by setting `url` and `params`, byutv will automatically establish a connection? Is that how it works?

2016-12-14 16:15 UTC, donnapep commented on .gitignore
> +rise-financial.html
@settinghead That sounds like a great idea! @stulees I think we should do that instead of committing those files to Github.

2016-12-14 16:18 UTC, stulees commented on .gitignore
> +rise-financial.html
@settinghead Nice, didn't know that was possible. @donnapep Agreed, so long as we can publish to contain those files I'm good with ignoring in git.

2016-12-14 16:18 UTC, donnapep commented on rise-financial-es6.js
> +      realTime.params = this._getRealTimeParams( instruments, fields );
@settinghead That's correct. It's what the [`auto` attribute](https://github.com/Rise-Vision/rise-financial/pull/6/files#diff-1c4ad2054a29419e2f296d322fd3b64eR8) does.

2016-12-14 16:25 UTC, stulees approved these changes

2016-12-14 16:26 UTC, stulees commented
@donnapep Looks good 👍 but will also defer to @settinghead

2016-12-14 16:45 UTC, donnapep commented
For the sake of expediency, I'm merging this now. @settinghead If you have any changes, let me know and I'll put them in my next PR. Thanks @stulees and @settinghead.

2016-12-14 16:45 UTC, merged

2016-12-14 16:46 UTC, settinghead commented
@donnapep no changes. Looks good. :+1: